/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Row shapes for the tables in `supabase/migrations/`.
 *
 * Hand-written rather than generated by `supabase gen types`, because that
 * command needs a running project and this file has to compile in CI, on a
 * fresh clone, and in the migration tests -- none of which have one. The trade
 * is that it can drift from the schema, so `schema.test.ts` asserts the columns
 * these types claim actually exist.
 *
 * Only the columns the client reads are modelled. Anything the client must not
 * write (points, grades, counters) is typed read-only at the call sites in
 * `src/lib/data/`, and enforced for real by row-level security.
 */

export type Topic = 'Algebra' | 'Geometry' | 'Combinatorics' | 'Number Theory';
export type Level = 'Foundation' | 'Advanced' | 'Olympiad';

export interface ProfileRow {
  id: string;
  username: string;
  display_name: string;
  avatar_url: string | null;
  bio: string | null;
  country: string | null;
  level: Level;
  follower_count: number;
  following_count: number;
  onboarded_at: string | null;
  created_at: string;
}

export interface UserStatsRow {
  user_id: string;
  points: number;
  attempts_total: number;
  attempts_correct: number;
  problems_solved: number;
  time_spent_seconds: number;
  current_streak: number;
  longest_streak: number;
  last_active_on: string | null;
}

export interface SkillMasteryRow {
  user_id: string;
  topic: Topic;
  attempts: number;
  correct: number;
  mastery: number;
  last_activity_at: string | null;
}

export interface LeaderboardRow {
  rank: number;
  user_id: string;
  username: string;
  display_name: string;
  avatar_url: string | null;
  country: string | null;
  level: Level;
  points: number;
  problems_solved: number;
  current_streak: number;
  accuracy_pct: number | null;
}

export interface PostRow {
  id: string;
  author_id: string;
  problem_id: string | null;
  community_id: string | null;
  body: string;
  like_count: number;
  comment_count: number;
  deleted_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface CommentRow {
  id: string;
  post_id: string;
  author_id: string;
  body: string;
  like_count: number;
  deleted_at: string | null;
  created_at: string;
}

export type NotificationType =
  | 'follow'
  | 'post_like'
  | 'comment_like'
  | 'post_comment'
  | 'message'
  | 'system';

export interface NotificationRow {
  id: string;
  user_id: string;
  actor_id: string | null;
  type: NotificationType;
  entity_type: 'post' | 'comment' | 'conversation' | 'profile' | null;
  entity_id: string | null;
  body: string | null;
  read_at: string | null;
  created_at: string;
}

export interface MessageRow {
  id: string;
  conversation_id: string;
  sender_id: string;
  body: string;
  deleted_at: string | null;
  created_at: string;
}

export interface ConversationRow {
  id: string;
  title: string | null;
  created_by: string | null;
  last_message_at: string | null;
  created_at: string;
}

/** A post joined with its author, which is how every feed renders one. */
export interface PostWithAuthor extends PostRow {
  author: Pick<ProfileRow, 'id' | 'username' | 'display_name' | 'avatar_url' | 'level'> | null;
  /** Whether the signed-in learner has liked this post. Absent when anonymous. */
  viewer_has_liked?: boolean;
  viewer_has_saved?: boolean;
}

export interface CommentWithAuthor extends CommentRow {
  author: Pick<ProfileRow, 'id' | 'username' | 'display_name' | 'avatar_url' | 'level'> | null;
}

export interface NotificationWithActor extends NotificationRow {
  actor: Pick<ProfileRow, 'id' | 'username' | 'display_name' | 'avatar_url'> | null;
}
