/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { IRTItem } from './irt';

/**
 * Calibrated item bank for the adaptive placement test.
 *
 * Organized by competition source to mirror the curriculum tiering:
 *   AMC 8  / AMC 10  -> Foundation
 *   AIME             -> Advanced
 *   USAMO / IMO      -> Olympiad
 *
 * IRT parameters:
 *   a — discrimination (how sharply the item separates ability around b)
 *   b — difficulty on the theta scale (-3 easiest .. +3 hardest)
 *   c — pseudo-guessing, ~1/4 for four-option multiple choice
 *
 * The `concept` tag drives knowledge-gap isolation and remediation dispatch.
 */
export const ITEM_BANK: IRTItem[] = [
  // ============================ AMC 8 ============================
  {
    id: 'amc8-alg-1',
    domain: 'Algebra',
    source: 'AMC 8',
    question: 'If $3x + 7 = 22$, what is the value of $x$?',
    options: ['5', '7', '3', '15'],
    correctIdx: 0,
    a: 1.1, b: -2.2, c: 0.25,
    hint: 'Subtract 7 from both sides, then divide by 3.',
    concept: 'Linear equations',
  },
  {
    id: 'amc8-geo-1',
    domain: 'Geometry',
    source: 'AMC 8',
    question: 'A rectangle has length 8 and width 5. What is its perimeter?',
    options: ['26', '40', '13', '30'],
    correctIdx: 0,
    a: 1.0, b: -2.4, c: 0.25,
    hint: 'Perimeter of a rectangle is $2(\\ell + w)$.',
    concept: 'Perimeter and area',
  },
  {
    id: 'amc8-comb-1',
    domain: 'Combinatorics',
    source: 'AMC 8',
    question: 'How many different two-digit numbers can be formed using the digits 1, 2, and 3 if digits may repeat?',
    options: ['9', '6', '3', '12'],
    correctIdx: 0,
    a: 1.2, b: -1.8, c: 0.25,
    hint: 'Three choices for the tens digit, three for the units digit.',
    concept: 'Multiplication principle',
  },
  {
    id: 'amc8-nt-1',
    domain: 'Number Theory',
    source: 'AMC 8',
    question: 'What is the greatest common divisor of 24 and 36?',
    options: ['12', '6', '18', '4'],
    correctIdx: 0,
    a: 1.1, b: -2.0, c: 0.25,
    hint: 'Factor both numbers into primes and take the shared factors.',
    concept: 'GCD and LCM',
  },
  {
    id: 'amc8-alg-2',
    domain: 'Algebra',
    source: 'AMC 8',
    question: 'The average of five numbers is 12. What is their sum?',
    options: ['60', '17', '12', '55'],
    correctIdx: 0,
    a: 1.3, b: -1.6, c: 0.25,
    hint: 'Average equals sum divided by count, so sum = average $\\times$ count.',
    concept: 'Averages',
  },
  {
    id: 'amc8-geo-2',
    domain: 'Geometry',
    source: 'AMC 8',
    question: 'In a triangle, two angles measure $50^\\circ$ and $60^\\circ$. What is the third angle?',
    options: ['$70^\\circ$', '$80^\\circ$', '$60^\\circ$', '$110^\\circ$'],
    correctIdx: 0,
    a: 1.2, b: -1.9, c: 0.25,
    hint: 'The interior angles of a triangle sum to $180^\\circ$.',
    concept: 'Angle chasing',
  },
  {
    id: 'amc8-nt-2',
    domain: 'Number Theory',
    source: 'AMC 8',
    question: 'What is the units digit of $7^{2}$?',
    options: ['9', '7', '1', '3'],
    correctIdx: 0,
    a: 1.0, b: -1.7, c: 0.25,
    hint: '$7^2 = 49$; look at the last digit.',
    concept: 'Units digits',
  },
  {
    id: 'amc8-comb-2',
    domain: 'Combinatorics',
    source: 'AMC 8',
    question: 'A bag has 4 red and 6 blue marbles. What is the probability a randomly drawn marble is red?',
    options: ['$2/5$', '$4/6$', '$1/4$', '$3/5$'],
    correctIdx: 0,
    a: 1.3, b: -1.5, c: 0.25,
    hint: 'Probability is favorable outcomes over total outcomes: $4/10$.',
    concept: 'Basic probability',
  },

  // ============================ AMC 10 ============================
  {
    id: 'amc10-alg-1',
    domain: 'Algebra',
    source: 'AMC 10',
    question: 'Find the sum of all real roots of $x^2 - 7x + 12 = 0$.',
    options: ['7', '12', '-7', '5'],
    correctIdx: 0,
    a: 1.4, b: -1.0, c: 0.25,
    hint: "By Vi\u00e8te's formulas, the sum of the roots is $-b/a$.",
    concept: "Vi\u00e8te's formulas",
  },
  {
    id: 'amc10-comb-1',
    domain: 'Combinatorics',
    source: 'AMC 10',
    question: 'In a room of 10 people, everyone shakes hands with everyone else exactly once. How many handshakes occur?',
    options: ['45', '90', '55', '100'],
    correctIdx: 0,
    a: 1.5, b: -0.9, c: 0.25,
    hint: 'Each handshake is a choice of 2 people from 10: $\\binom{10}{2}$.',
    concept: 'Combinations',
  },
  {
    id: 'amc10-geo-1',
    domain: 'Geometry',
    source: 'AMC 10',
    question: 'A triangle has side lengths 5, 12, and 13. What is its area?',
    options: ['30', '60', '39', '32.5'],
    correctIdx: 0,
    a: 1.4, b: -0.8, c: 0.25,
    hint: 'Check the converse Pythagorean theorem: $5^2 + 12^2 = 13^2$.',
    concept: 'Right triangles',
  },
  {
    id: 'amc10-nt-1',
    domain: 'Number Theory',
    source: 'AMC 10',
    question: 'What is the smallest positive integer with exactly 3 distinct positive divisors?',
    options: ['4', '6', '9', '8'],
    correctIdx: 0,
    a: 1.5, b: -0.5, c: 0.25,
    hint: 'A number has exactly 3 divisors precisely when it is the square of a prime.',
    concept: 'Divisor counting',
  },
  {
    id: 'amc10-nt-2',
    domain: 'Number Theory',
    source: 'AMC 10',
    question: 'Find the remainder when $3^{2026}$ is divided by 5.',
    options: ['4', '1', '3', '2'],
    correctIdx: 0,
    a: 1.6, b: -0.2, c: 0.25,
    hint: 'Powers of 3 cycle mod 5 with period 4; reduce the exponent $2026 \\bmod 4$.',
    concept: 'Modular arithmetic',
  },
  {
    id: 'amc10-alg-2',
    domain: 'Algebra',
    source: 'AMC 10',
    question: 'Suppose $f(f(x)) = x + 2$ for all real $x$. Which linear function could $f$ be?',
    options: ['$f(x) = x + 1$', '$f(x) = x + 2$', '$f(x) = -x + 1$', 'No linear function works'],
    correctIdx: 0,
    a: 1.5, b: 0.1, c: 0.25,
    hint: 'Try $f(x) = x + c$ and solve: $(x + c) + c = x + 2c = x + 2$.',
    concept: 'Functional equations',
  },
  {
    id: 'amc10-comb-2',
    domain: 'Combinatorics',
    source: 'AMC 10',
    question: 'How many ways can 4 students sit around a round table, where rotations are considered identical?',
    options: ['6', '24', '12', '4'],
    correctIdx: 0,
    a: 1.6, b: -0.3, c: 0.25,
    hint: 'Fix one seat as a reference point: $(n-1)! = 3!$.',
    concept: 'Circular permutations',
  },
  {
    id: 'amc10-geo-2',
    domain: 'Geometry',
    source: 'AMC 10',
    question: 'What is the sum of the interior angles of a convex hexagon?',
    options: ['$720^\\circ$', '$540^\\circ$', '$900^\\circ$', '$1080^\\circ$'],
    correctIdx: 0,
    a: 1.3, b: -0.7, c: 0.25,
    hint: 'For a convex $n$-gon the sum is $(n-2) \\cdot 180^\\circ$.',
    concept: 'Polygon angles',
  },
  {
    id: 'amc10-alg-3',
    domain: 'Algebra',
    source: 'AMC 10',
    question: 'If $a + b + c = 1$ for positive reals, what is the minimum of $\\frac{1}{a} + \\frac{1}{b} + \\frac{1}{c}$?',
    options: ['9', '3', '1', '6'],
    correctIdx: 0,
    a: 1.7, b: 0.4, c: 0.25,
    hint: 'Apply Cauchy-Schwarz in Engel form, or AM-HM.',
    concept: 'Inequalities',
  },

  // ============================ AIME ============================
  {
    id: 'aime-geo-1',
    domain: 'Geometry',
    source: 'AIME',
    question: 'A cyclic quadrilateral has consecutive sides 3, 4, 5, 6. Its area is $\\sqrt{N}$. Find $N$.',
    options: ['360', '340', '380', '400'],
    correctIdx: 0,
    a: 1.8, b: 0.7, c: 0.25,
    hint: "Brahmagupta's formula: $S = \\sqrt{(p-a)(p-b)(p-c)(p-d)}$ with $p$ the semiperimeter.",
    concept: 'Cyclic quadrilaterals',
  },
  {
    id: 'aime-comb-1',
    domain: 'Combinatorics',
    source: 'AIME',
    question: '5 boys and 3 girls stand in a row. How many arrangements have no two girls adjacent?',
    options: ['14400', '2880', '40320', '7200'],
    correctIdx: 0,
    a: 1.9, b: 0.9, c: 0.25,
    hint: 'Arrange the boys first, then place girls into the gaps between and around them.',
    concept: 'Gap method',
  },
  {
    id: 'aime-nt-1',
    domain: 'Number Theory',
    source: 'AIME',
    question: 'How many positive integers less than 120 are relatively prime to 120?',
    options: ['32', '40', '48', '24'],
    correctIdx: 0,
    a: 1.8, b: 0.8, c: 0.25,
    hint: "Use Euler's totient: $\\varphi(n) = n\\prod_{p \\mid n}(1 - 1/p)$.",
    concept: "Euler's totient function",
  },
  {
    id: 'aime-alg-1',
    domain: 'Algebra',
    source: 'AIME',
    question: 'Let $x + \\frac{1}{x} = 5$. Find $x^3 + \\frac{1}{x^3}$.',
    options: ['110', '125', '95', '140'],
    correctIdx: 0,
    a: 1.9, b: 0.6, c: 0.25,
    hint: 'Use $x^3 + 1/x^3 = (x + 1/x)^3 - 3(x + 1/x)$.',
    concept: 'Symmetric expressions',
  },
  {
    id: 'aime-geo-2',
    domain: 'Geometry',
    source: 'AIME',
    question: 'Equilateral $\\triangle ABC$ is inscribed in a circle, and $M$ lies on minor arc $BC$. If $MB = 5$ and $MC = 8$, find $MA$.',
    options: ['13', '12', '40', '3'],
    correctIdx: 0,
    a: 2.0, b: 1.1, c: 0.25,
    hint: "Apply Ptolemy's theorem to cyclic quadrilateral $ABMC$.",
    concept: "Ptolemy's theorem",
  },
  {
    id: 'aime-comb-2',
    domain: 'Combinatorics',
    source: 'AIME',
    question: 'How many non-negative integer solutions does $x + y + z = 10$ have?',
    options: ['66', '55', '78', '45'],
    correctIdx: 0,
    a: 1.8, b: 0.5, c: 0.25,
    hint: 'Stars and bars: $\\binom{n + k - 1}{k - 1}$ with $n = 10$, $k = 3$.',
    concept: 'Stars and bars',
  },
  {
    id: 'aime-nt-2',
    domain: 'Number Theory',
    source: 'AIME',
    question: 'Find the remainder when $2^{100}$ is divided by 125.',
    options: ['1', '51', '26', '76'],
    correctIdx: 0,
    a: 2.0, b: 1.3, c: 0.25,
    hint: "$\\varphi(125) = 100$ and $\\gcd(2,125)=1$, so Euler's theorem applies directly.",
    concept: "Euler's theorem",
  },
  {
    id: 'aime-alg-2',
    domain: 'Algebra',
    source: 'AIME',
    question: 'The polynomial $x^3 - 6x^2 + 11x - 6$ has roots $r, s, t$. Find $r^2 + s^2 + t^2$.',
    options: ['14', '36', '11', '25'],
    correctIdx: 0,
    a: 1.9, b: 1.0, c: 0.25,
    hint: 'Use $r^2+s^2+t^2 = (r+s+t)^2 - 2(rs+st+tr)$ with Vi\u00e8te.',
    concept: 'Newton sums',
  },

  // ============================ USAMO ============================
  {
    id: 'usamo-comb-1',
    domain: 'Combinatorics',
    source: 'USAMO',
    question: 'A simple graph on 10 vertices has no triangle. What is the maximum possible number of edges?',
    options: ['25', '45', '20', '30'],
    correctIdx: 0,
    a: 2.1, b: 1.6, c: 0.25,
    hint: "Mantel's theorem: a triangle-free graph has at most $\\lfloor n^2/4 \\rfloor$ edges.",
    concept: "Mantel's theorem",
  },
  {
    id: 'usamo-nt-1',
    domain: 'Number Theory',
    source: 'USAMO',
    question: 'How many positive integer pairs $(x, y)$ satisfy $x^2 - y! = 2026$?',
    options: ['0', '1', '2', 'Infinitely many'],
    correctIdx: 0,
    a: 2.2, b: 1.9, c: 0.25,
    hint: 'Work modulo 7: for $y \\ge 7$, $y! \\equiv 0$, forcing $x^2 \\equiv 3 \\pmod 7$ — impossible.',
    concept: 'Diophantine equations',
  },
  {
    id: 'usamo-geo-1',
    domain: 'Geometry',
    source: 'USAMO',
    question: 'The Euler line of a non-equilateral triangle passes through which three centers?',
    options: [
      'Orthocenter, centroid, circumcenter',
      'Incenter, centroid, orthocenter',
      'Incenter, orthocenter, circumcenter',
      'Incenter, centroid, circumcenter',
    ],
    correctIdx: 0,
    a: 2.0, b: 1.5, c: 0.25,
    hint: 'Euler proved $H$, $G$, $O$ are collinear with $HG = 2 \\cdot GO$.',
    concept: 'Euler line',
  },
  {
    id: 'usamo-alg-1',
    domain: 'Algebra',
    source: 'USAMO',
    question: 'How many distinct real pairs $(x,y)$ satisfy $x^2 + 2x\\sin(xy) + 1 = 0$?',
    options: ['Infinitely many', 'Exactly one', 'Exactly two', 'None'],
    correctIdx: 0,
    a: 2.2, b: 2.0, c: 0.25,
    hint: 'Rewrite as $(x + \\sin(xy))^2 + \\cos^2(xy) = 0$, forcing both terms to vanish.',
    concept: 'Trigonometric identities',
  },
  {
    id: 'usamo-comb-2',
    domain: 'Combinatorics',
    source: 'USAMO',
    question: 'An $8 \\times 8$ board has two opposite corners removed. How many dominoes tile it?',
    options: ['It cannot be tiled', '31', '32', '30'],
    correctIdx: 0,
    a: 2.1, b: 1.7, c: 0.25,
    hint: 'Colour the board like a checkerboard — opposite corners share a colour.',
    concept: 'Colouring arguments',
  },
  {
    id: 'usamo-alg-2',
    domain: 'Algebra',
    source: 'USAMO',
    question: 'For positive reals with $abc = 1$, what is the minimum of $a + b + c$?',
    options: ['3', '1', '2', 'No minimum exists'],
    correctIdx: 0,
    a: 2.0, b: 1.4, c: 0.25,
    hint: 'AM-GM: $a+b+c \\ge 3\\sqrt[3]{abc}$, with equality when $a=b=c$.',
    concept: 'AM-GM inequality',
  },

  // ============================ IMO ============================
  {
    id: 'imo-nt-1',
    domain: 'Number Theory',
    source: 'IMO',
    question: 'If $p$ is prime and $p \\mid a^2 + b^2$ with $p \\equiv 3 \\pmod 4$, what must be true?',
    options: [
      '$p \\mid a$ and $p \\mid b$',
      '$p \\mid a$ or $p \\mid b$, not both',
      '$p \\mid a + b$ only',
      'Nothing further is forced',
    ],
    correctIdx: 0,
    a: 2.3, b: 2.4, c: 0.25,
    hint: '$-1$ is a quadratic non-residue mod $p$ when $p \\equiv 3 \\pmod 4$.',
    concept: 'Quadratic residues',
  },
  {
    id: 'imo-comb-1',
    domain: 'Combinatorics',
    source: 'IMO',
    question: 'What is the minimum number of people needed to guarantee 3 mutual friends or 3 mutual strangers?',
    options: ['6', '5', '9', '7'],
    correctIdx: 0,
    a: 2.2, b: 2.1, c: 0.25,
    hint: 'This is the Ramsey number $R(3,3)$.',
    concept: 'Ramsey theory',
  },
  {
    id: 'imo-geo-1',
    domain: 'Geometry',
    source: 'IMO',
    question: 'In $\\triangle ABC$, the incircle touches $BC$ at $X$. If $a, b, c$ are the side lengths and $s$ the semiperimeter, then $BX =$',
    options: ['$s - b$', '$s - a$', '$s - c$', '$s/2$'],
    correctIdx: 0,
    a: 2.2, b: 2.2, c: 0.25,
    hint: 'Equal tangent segments from each vertex give $BX = s - b$.',
    concept: 'Incircle tangency',
  },
  {
    id: 'imo-alg-1',
    domain: 'Algebra',
    source: 'IMO',
    question: 'Find all functions $f:\\mathbb{R}\\to\\mathbb{R}$ with $f(x+y) = f(x) + f(y)$ and $f$ continuous. Then $f(x) =$',
    options: ['$cx$ for some constant $c$', '$c$ for some constant $c$', '$x^2$', '$e^x$'],
    correctIdx: 0,
    a: 2.3, b: 2.0, c: 0.25,
    hint: "Cauchy's functional equation with a continuity assumption forces linearity.",
    concept: "Cauchy's functional equation",
  },
  {
    id: 'imo-nt-2',
    domain: 'Number Theory',
    source: 'IMO',
    question: 'For how many positive integers $n < 100$ is $n^2 + n + 1$ divisible by 7?',
    options: ['28', '14', '33', '20'],
    correctIdx: 0,
    a: 2.1, b: 2.3, c: 0.25,
    hint: 'Check $n \\bmod 7$; the condition holds for exactly two residue classes.',
    concept: 'Polynomial congruences',
  },
  {
    id: 'imo-geo-2',
    domain: 'Geometry',
    source: 'IMO',
    question: 'Point $P$ is inside equilateral $\\triangle ABC$. The sum of distances from $P$ to the three sides equals',
    options: [
      'The triangle\u2019s altitude',
      'The triangle\u2019s side length',
      'Half the perimeter',
      'It varies with $P$',
    ],
    correctIdx: 0,
    a: 2.2, b: 1.9, c: 0.25,
    hint: "Viviani's theorem — compare areas of the three sub-triangles.",
    concept: "Viviani's theorem",
  },
];

/** Groups items by their competition source, for reporting and bank browsing. */
export function itemsBySource() {
  const groups = new Map<string, IRTItem[]>();
  for (const item of ITEM_BANK) {
    const list = groups.get(item.source) || [];
    list.push(item);
    groups.set(item.source, list);
  }
  return groups;
}
