/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { IRTItem } from './irt';

/**
 * Multiple-choice item bank used only by the adaptive placement test.
 * Each item ID/comment identifies its source dataset and original problem.
 * AMC 8 / AMC 10 `source` values remain the existing placement level bands;
 * the AMC questions themselves are from AMC 12, as the IDs record.
 * IRT a/b values remain provisional content-routing estimates, not fitted
 * psychometric calibrations. c matches the number of choices (1/5 or 1/4).
 */
export const ITEM_BANK: IRTItem[] = [
  // edev2000/amc12-full · 2022A-P1
  {
    id: "amc12-2022a-p1",
    domain: "Algebra",
    source: "AMC 8",
    question: "What is the value of $$ 3+\\frac{1}{3+\\frac{1}{3+\\frac13}}? $$",
    options: ["$\\frac{31}{10}$", "$\\frac{49}{15}$", "$\\frac{33}{10}$", "$\\frac{109}{33}$", "$\\frac{15}{4}$"],
    correctIdx: 3,
    a: 1.2,
    b: -1.8,
    c: 0.2,
    hint: "Work from the innermost fraction outward.",
    concept: "Continued fractions",
  },
  // edev2000/amc12-full · 2022A-P2
  {
    id: "amc12-2022a-p2",
    domain: "Algebra",
    source: "AMC 8",
    question: "The sum of three numbers is $96.$ The first number is $6$ times the third number, and the third number is $40$ less than the second number. What is the absolute value of the difference between the first and second numbers?",
    options: ["$1$", "$2$", "$3$", "$4$", "$5$"],
    correctIdx: 4,
    a: 1.2,
    b: -1.7,
    c: 0.2,
    hint: "Express all three numbers using the third number.",
    concept: "Linear equations",
  },
  // edev2000/amc12-full · 2022A-P4
  {
    id: "amc12-2022a-p4",
    domain: "Number Theory",
    source: "AMC 8",
    question: "The least common multiple of a positive integer $n$ and $18$ is $180$, and the greatest common divisor of $n$ and $45$ is $15$. What is the sum of the digits of $n$?",
    options: ["$3$", "$6$", "$8$", "$9$", "$12$"],
    correctIdx: 1,
    a: 1.2,
    b: -1.6,
    c: 0.2,
    hint: "Use the prime factorizations of 18, 45, and 180.",
    concept: "GCD and LCM",
  },
  // edev2000/amc12-full · 2022A-P5
  {
    id: "amc12-2022a-p5",
    domain: "Geometry",
    source: "AMC 8",
    question: "The taxicab distance between points $(x_1, y_1)$ and $(x_2, y_2)$ in the coordinate plane is given by $$ |x_1 - x_2| + |y_1 - y_2|. $$ For how many points $P$ with integer coordinates is the taxicab distance between $P$ and the origin less than or equal to $20$?",
    options: ["$441$", "$761$", "$841$", "$921$", "$924$"],
    correctIdx: 2,
    a: 1.2,
    b: -1.5,
    c: 0.2,
    hint: "Count the lattice points on each diamond of fixed radius.",
    concept: "Taxicab distance",
  },
  // edev2000/amc12-full · 2022A-P6
  {
    id: "amc12-2022a-p6",
    domain: "Algebra",
    source: "AMC 8",
    question: "A data set consists of $6$ (not distinct) positive integers: $1$, $7$, $5$, $2$, $5$, and $X$. The average (arithmetic mean) of the $6$ numbers equals a value in the data set. What is the sum of all possible values of $X$?",
    options: ["$10$", "$26$", "$32$", "$36$", "$40$"],
    correctIdx: 3,
    a: 1.2,
    b: -1.4,
    c: 0.2,
    hint: "The mean must equal one of the six listed numbers.",
    concept: "Averages",
  },
  // edev2000/amc12-full · 2022A-P8
  {
    id: "amc12-2022a-p8",
    domain: "Algebra",
    source: "AMC 8",
    question: "The infinite product $$ \\sqrt[3]{10} \\cdot \\sqrt[3]{\\sqrt[3]{10}} \\cdot \\sqrt[3]{\\sqrt[3]{\\sqrt[3]{10}}} \\cdots $$ evaluates to a real number. What is that number?",
    options: ["$\\sqrt{10}$", "$\\sqrt[3]{100}$", "$\\sqrt[4]{1000}$", "$10$", "$10\\sqrt[3]{10}$"],
    correctIdx: 0,
    a: 1.2,
    b: -1.2,
    c: 0.2,
    hint: "Add the exponents of 10 as a geometric series.",
    concept: "Infinite products",
  },
  // edev2000/amc12-full · 2022A-P10
  {
    id: "amc12-2022a-p10",
    domain: "Combinatorics",
    source: "AMC 10",
    question: "How many ways are there to split the integers $1$ through $14$ into $7$ pairs such that in each pair, the greater number is at least $2$ times the lesser number?",
    options: ["$108$", "$120$", "$126$", "$132$", "$144$"],
    correctIdx: 4,
    a: 1.6,
    b: 0.0,
    c: 0.2,
    hint: "The largest seven numbers must pair with the smallest seven.",
    concept: "Pairings",
  },
  // edev2000/amc12-full · 2022A-P12
  {
    id: "amc12-2022a-p12",
    domain: "Geometry",
    source: "AMC 10",
    question: "Let $M$ be the midpoint of $\\overline{AB}$ in regular tetrahedron $ABCD$. What is $\\cos(\\angle CMD)$?",
    options: ["$\\frac14$", "$\\frac13$", "$\\frac25$", "$\\frac12$", "$\\frac{\\sqrt{3}}{2}$"],
    correctIdx: 1,
    a: 1.6,
    b: 0.1,
    c: 0.2,
    hint: "Use coordinates for a regular tetrahedron and the dot product.",
    concept: "Spatial geometry",
  },
  // edev2000/amc12-full · 2022B-P4
  {
    id: "amc12-2022b-p4",
    domain: "Algebra",
    source: "AMC 8",
    question: "For how many values of the constant $k$ will the polynomial $x^{2}+kx+36$ have two distinct integer roots?",
    options: ["$6$", "$8$", "$9$", "$14$", "$16$"],
    correctIdx: 1,
    a: 1.2,
    b: -1.3,
    c: 0.2,
    hint: "Count factor pairs of 36 that give distinct roots.",
    concept: "Integer roots",
  },
  // edev2000/amc12-full · 2022B-P5
  {
    id: "amc12-2022b-p5",
    domain: "Geometry",
    source: "AMC 8",
    question: "The point $(-1, -2)$ is rotated $270^{\\circ}$ counterclockwise about the point $(3, 1)$. What are the coordinates of its new position?",
    options: ["$(-3, -4)$", "$(0,5)$", "$(2,-1)$", "$(4,3)$", "$(6,-3)$"],
    correctIdx: 1,
    a: 1.2,
    b: -1.7,
    c: 0.2,
    hint: "Translate to the rotation center, rotate, then translate back.",
    concept: "Coordinate rotations",
  },
  // edev2000/amc12-full · 2022B-P6
  {
    id: "amc12-2022b-p6",
    domain: "Combinatorics",
    source: "AMC 10",
    question: "Consider the following $100$ sets of $10$ elements each: $$ \\begin{align*} &\\{1,2,3,\\ldots,10\\}, \\\\ &\\{11,12,13,\\ldots,20\\},\\\\ &\\{21,22,23,\\ldots,30\\},\\\\ &\\vdots\\\\ &\\{991,992,993,\\ldots,1000\\}. \\end{align*} $$ How many of these sets contain exactly two multiples of $7$?",
    options: ["$40$", "$42$", "$43$", "$49$", "$50$"],
    correctIdx: 1,
    a: 1.2,
    b: -0.5,
    c: 0.2,
    hint: "Each block has ten consecutive integers; inspect residues modulo 7.",
    concept: "Counting multiples",
  },
  // edev2000/amc12-full · 2022B-P10
  {
    id: "amc12-2022b-p10",
    domain: "Geometry",
    source: "AMC 10",
    question: "Regular hexagon $ABCDEF$ has side length $2$. Let $G$ be the midpoint of $\\overline{AB}$, and let $H$ be the midpoint of $\\overline{DE}$. What is the perimeter of $GCHF$?",
    options: ["$4\\sqrt3$", "$8$", "$4\\sqrt5$", "$4\\sqrt7$", "$12$"],
    correctIdx: 3,
    a: 1.2,
    b: -0.2,
    c: 0.2,
    hint: "Place the hexagon on a coordinate plane.",
    concept: "Regular polygons",
  },
  // edev2000/amc12-full · 2022B-P12
  {
    id: "amc12-2022b-p12",
    domain: "Combinatorics",
    source: "AMC 10",
    question: "Kayla rolls four fair $6$-sided dice. What is the probability that at least one of the numbers Kayla rolls is greater than $4$ and at least two of the numbers she rolls are greater than $2$?",
    options: ["$\\frac{2}{3}$", "$\\frac{19}{27}$", "$\\frac{59}{81}$", "$\\frac{61}{81}$", "$\\frac{7}{9}$"],
    correctIdx: 3,
    a: 1.6,
    b: 0.2,
    c: 0.2,
    hint: "Count the complement using dice in the ranges 1–2, 3–4, and 5–6.",
    concept: "Probability",
  },
  // edev2000/amc12-full · 2022B-P14
  {
    id: "amc12-2022b-p14",
    domain: "Geometry",
    source: "AMC 10",
    question: "The graph of $y=x^2+2x-15$ intersects the $x$-axis at points $A$ and $C$ and the $y$-axis at point $B$. What is $\\tan(\\angle ABC)$?",
    options: ["$\\frac{1}{7}$", "$\\frac{1}{4}$", "$\\frac{3}{7}$", "$\\frac{1}{2}$", "$\\frac{4}{7}$"],
    correctIdx: 4,
    a: 1.6,
    b: 0.2,
    c: 0.2,
    hint: "Find the intercepts and compare the slopes of BA and BC.",
    concept: "Analytic geometry",
  },
  // edev2000/amc12-full · 2022B-P15
  {
    id: "amc12-2022b-p15",
    domain: "Number Theory",
    source: "AMC 10",
    question: "One of the following numbers is not divisible by any prime number less than $10.$ Which is it?",
    options: ["$2^{606}-1$", "$2^{606}+1$", "$2^{607}-1$", "$2^{607}+1$", "$2^{607}+3^{607}$"],
    correctIdx: 2,
    a: 1.6,
    b: 0.3,
    c: 0.2,
    hint: "Test each expression modulo 2, 3, 5, and 7.",
    concept: "Divisibility",
  },
  // edev2000/amc12-full · 2023A-P3
  {
    id: "amc12-2023a-p3",
    domain: "Number Theory",
    source: "AMC 8",
    question: "How many positive perfect squares less than $2023$ are divisible by $5$?",
    options: ["$8$", "$9$", "$10$", "$11$", "$12$"],
    correctIdx: 0,
    a: 1.2,
    b: -1.9,
    c: 0.2,
    hint: "A square is divisible by 5 exactly when its root is.",
    concept: "Perfect squares",
  },
  // edev2000/amc12-full · 2023A-P4
  {
    id: "amc12-2023a-p4",
    domain: "Number Theory",
    source: "AMC 8",
    question: "How many digits are in the base-ten representation of $8^5 \\cdot 5^{10} \\cdot 15^5$?",
    options: ["$14$", "$15$", "$16$", "$17$", "$18$"],
    correctIdx: 4,
    a: 1.2,
    b: -1.4,
    c: 0.2,
    hint: "Rewrite the product as a power of 10 times a power of 3.",
    concept: "Prime factorization",
  },
  // edev2000/amc12-full · 2023A-P10
  {
    id: "amc12-2023a-p10",
    domain: "Algebra",
    source: "AMC 10",
    question: "Positive real numbers $x$ and $y$ satisfy $y^3 = x^2$ and $(y-x)^2 = 4y^2$. What is $x+y$?",
    options: ["$12$", "$18$", "$24$", "$36$", "$42$"],
    correctIdx: 3,
    a: 1.2,
    b: -0.5,
    c: 0.2,
    hint: "Use positivity to choose the correct sign after taking a square root.",
    concept: "Systems of equations",
  },
  // edev2000/amc12-full · 2023A-P11
  {
    id: "amc12-2023a-p11",
    domain: "Geometry",
    source: "AMC 8",
    question: "What is the degree measure of the acute angle formed by lines with slopes $2$ and $\\tfrac{1}{3}$?",
    options: ["$30$", "$37.5$", "$45$", "$52.5$", "$60$"],
    correctIdx: 2,
    a: 1.2,
    b: -1.0,
    c: 0.2,
    hint: "Use the tangent formula for the angle between two slopes.",
    concept: "Angles between lines",
  },
  // edev2000/amc12-full · 2023A-P12
  {
    id: "amc12-2023a-p12",
    domain: "Algebra",
    source: "AMC 10",
    question: "What is the value of $$ 2^3 - 1^3 + 4^3 - 3^3 + 6^3 - 5^3 + \\dots + 18^3 - 17^3?",
    options: ["$2023$", "$2679$", "$2941$", "$3159$", "$3235$"],
    correctIdx: 3,
    a: 1.2,
    b: -0.3,
    c: 0.2,
    hint: "Pair consecutive cubes before summing.",
    concept: "Sums of powers",
  },
  // edev2000/amc12-full · 2023B-P8
  {
    id: "amc12-2023b-p8",
    domain: "Combinatorics",
    source: "AMC 10",
    question: "How many nonempty subsets $B$ of $\\{0, 1, 2, 3, \\dots, 12\\}$ have the property that the number of elements in $B$ is equal to the least element of $B$? For example, $B = \\{4, 6, 8, 11\\}$ satisfies the condition.",
    options: ["$256$", "$136$", "$108$", "$144$", "$156$"],
    correctIdx: 3,
    a: 1.6,
    b: 0.1,
    c: 0.2,
    hint: "Fix the least element, then choose the other elements.",
    concept: "Subset counting",
  },
  // edev2000/amc12-full · 2023B-P14
  {
    id: "amc12-2023b-p14",
    domain: "Number Theory",
    source: "AMC 10",
    question: "For how many ordered pairs $(a,b)$ of integers does the polynomial $x^3+ax^2+bx+6$ have $3$ distinct integer roots?",
    options: ["$5$", "$6$", "$8$", "$7$", "$4$"],
    correctIdx: 0,
    a: 1.6,
    b: 0.2,
    c: 0.2,
    hint: "The three distinct roots have product -6.",
    concept: "Integer roots",
  },
  // edev2000/amc12-full · 2023B-P16
  {
    id: "amc12-2023b-p16",
    domain: "Number Theory",
    source: "AMC 10",
    question: "In Coinland, there are three types of coins, each worth $6, 10,$ and $15.$ What is the sum of the digits of the maximum amount of money that is impossible to have?",
    options: ["$8$", "$10$", "$7$", "$11$", "$9$"],
    correctIdx: 3,
    a: 1.6,
    b: 0.2,
    c: 0.2,
    hint: "Find the largest unattainable amount using residues modulo 6.",
    concept: "Coin problem",
  },
  // edev2000/amc12-full · 2023B-P19
  {
    id: "amc12-2023b-p19",
    domain: "Combinatorics",
    source: "AMC 10",
    question: "Each of $2023$ balls is placed in one of $3$ bins. Which of the following is closest to the probability that each of the bins will contain an odd number of balls?",
    options: ["$\\frac{2}{3}$", "$\\frac{3}{10}$", "$\\frac{1}{2}$", "$\\frac{1}{3}$", "$\\frac{1}{4}$"],
    correctIdx: 4,
    a: 1.6,
    b: 0.3,
    c: 0.2,
    hint: "Track the parity of the three bin counts.",
    concept: "Parity probability",
  },
  // edev2000/amc12-full · 2023B-P23
  {
    id: "amc12-2023b-p23",
    domain: "Combinatorics",
    source: "AMC 10",
    question: "When $n$ standard six-sided dice are rolled, the product of the numbers rolled can be any of $936$ possible values. What is $n$?",
    options: ["$11$", "$6$", "$8$", "$10$", "$9$"],
    correctIdx: 0,
    a: 1.6,
    b: 0.3,
    c: 0.2,
    hint: "Count distinct prime-exponent vectors for products of dice rolls.",
    concept: "Product counting",
  },
  // MathArena/aime_2025 · problem 1
  {
    id: "aime-2025-p1",
    domain: "Number Theory",
    source: "AIME",
    question: "Find the sum of all integer bases $b>9$ for which $17_b$ is a divisor of $97_b.$",
    options: ["70", "60", "80", "90"],
    correctIdx: 0,
    a: 1.8,
    b: 0.5,
    c: 0.25,
    hint: "Write $17_b=b+7$ and $97_b=9b+7$, then use divisibility.",
    concept: "Numeral bases",
  },
  // MathArena/aime_2025 · problem 3
  {
    id: "aime-2025-p3",
    domain: "Combinatorics",
    source: "AIME",
    question: "The 9 members of a baseball team went to an ice-cream parlor after their game. Each player had a singlescoop cone of chocolate, vanilla, or strawberry ice cream. At least one player chose each flavor, and the number of players who chose chocolate was greater than the number of players who chose vanilla, which was greater than the number of players who chose strawberry. Let $N$ be the number of different assignments of flavors to players that meet these conditions. Find the remainder when $N$ is divided by $1000.$",
    options: ["16", "24", "48", "96"],
    correctIdx: 0,
    a: 1.8,
    b: 1.0,
    c: 0.25,
    hint: "List the possible strictly decreasing positive flavor counts before assigning players.",
    concept: "Multinomial counting",
  },
  // MathArena/aime_2025 · problem 4
  {
    id: "aime-2025-p4",
    domain: "Algebra",
    source: "AIME",
    question: "Find the number of ordered pairs $(x,y)$, where both $x$ and $y$ are integers between $-100$ and $100$, inclusive, such that $12x^2-xy-6y^2=0$.",
    options: ["117", "101", "201", "234"],
    correctIdx: 0,
    a: 1.8,
    b: 0.8,
    c: 0.25,
    hint: "Factor the quadratic expression and bound the integer parameter.",
    concept: "Diophantine equations",
  },
  // MathArena/aime_2025 · problem 6
  {
    id: "aime-2025-p6",
    domain: "Geometry",
    source: "AIME",
    question: "An isosceles trapezoid has an inscribed circle tangent to each of its four sides. The radius of the circle is $3$, and the area of the trapezoid is $72$. Let the parallel sides of the trapezoid have lengths $r$ and $s$, with $r \\neq s$. Find $r^2+s^2$",
    options: ["504", "432", "576", "648"],
    correctIdx: 0,
    a: 1.8,
    b: 1.1,
    c: 0.25,
    hint: "Use area = inradius times semiperimeter for a tangential quadrilateral.",
    concept: "Tangential trapezoids",
  },
  // MathArena/aime_2025 · problem 17
  {
    id: "aime-2025-p17",
    domain: "Number Theory",
    source: "AIME",
    question: "Find the sum of all positive integers $n$ such that $n+2$ divides the product $3(n+3)(n^2+9)$.",
    options: ["49", "21", "35", "63"],
    correctIdx: 0,
    a: 1.8,
    b: 1.3,
    c: 0.25,
    hint: "Reduce the polynomial modulo $n+2$ to get a fixed divisor.",
    concept: "Polynomial congruences",
  },
  // MathArena/aime_2026 · problem 2
  {
    id: "aime-2026-p2",
    domain: "Combinatorics",
    source: "AIME",
    question: "Find the number of positive integer palindromes written in base $10$ with no zero digits, and whose digits add up to $13$. For example, $42124$ has these properties. Recall that a palindrome is a number whose representation reads the same from left to right as from right to left.",
    options: ["62", "52", "72", "82"],
    correctIdx: 0,
    a: 1.8,
    b: 0.9,
    c: 0.25,
    hint: "Separate palindromes of even and odd length.",
    concept: "Palindrome counting",
  },
  // MathArena/aime_2026 · problem 4
  {
    id: "aime-2026-p4",
    domain: "Number Theory",
    source: "AIME",
    question: "Find the number of integers less than or equal to 100 that are equal to $a+b+ab$ for some choice of distinct positive integers a and b.",
    options: ["70", "64", "72", "75"],
    correctIdx: 0,
    a: 1.8,
    b: 0.7,
    c: 0.25,
    hint: "Rewrite $a+b+ab$ as $(a+1)(b+1)-1$.",
    concept: "Divisor counting",
  },
  // MathArena/aime_2026 · problem 16
  {
    id: "aime-2026-p16",
    domain: "Algebra",
    source: "AIME",
    question: "Find the sum of the $10$th terms of all arithmetic sequences of integers that have first term equal to $4$ and include both $24$ and $34$ as terms.",
    options: ["178", "168", "188", "198"],
    correctIdx: 0,
    a: 1.8,
    b: 1.2,
    c: 0.25,
    hint: "The common difference must divide both $24-4$ and $34-4$.",
    concept: "Arithmetic sequences",
  },
  // MathArena/usamo_2024 · problem 1
  {
    id: "usamo-2024-p1",
    domain: "Number Theory",
    source: "USAMO",
    question: "Find all integers $n \\geq 3$ such that the following property holds: if we list the divisors of $n!$ in increasing order as $1 = d_1 < d_2 < \\dots < d_k = n!$, then we have \\[ d_2 - d_1 \\leq d_3 - d_2 \\leq \\dots \\leq d_k - d_{k-1}. \\]",
    options: ["$n=3,4$", "$n=3$ only", "$n=4,5$", "$n=3,4,5$"],
    correctIdx: 0,
    a: 2.0,
    b: 1.7,
    c: 0.25,
    hint: "Compare gaps near the smallest integer that fails to divide $n!$.",
    concept: "Divisor order",
  },
  // MathArena/usamo_2026 · problem 1
  {
    id: "usamo-2026-p1",
    domain: "Algebra",
    source: "USAMO",
    question: "For an integer $n>1$, what is the maximum over real $x$ of $\\lfloor nx\\rfloor-\\sum_{k=1}^{n}\\frac{\\lfloor kx\\rfloor}{k}$?",
    options: ["$\\sum_{k=1}^{n}\\frac1k-1$", "$\\sum_{k=1}^{n}\\frac1k$", "$n-1$", "$1-\\frac1n$"],
    correctIdx: 0,
    a: 2.0,
    b: 1.9,
    c: 0.25,
    hint: "The expression is periodic in $x$; inspect $x$ just below an integer.",
    concept: "Floor functions",
  },
  // MathArena/usamo_2026 · problem 4
  {
    id: "usamo-2026-p4",
    domain: "Number Theory",
    source: "USAMO",
    question: "A positive integer $n$ is solitary if every decomposition $n=a+b$ into nonnegative integers has a digit 1 in $a$ or $b$. How many solitary integers are less than $10^{2026}$?",
    options: ["$2^{2026}-1$", "$2^{2026}$", "$2^{2025}-1$", "$10^{2026}-1$"],
    correctIdx: 0,
    a: 2.0,
    b: 2.1,
    c: 0.25,
    hint: "Characterize the decimal digits of $n+1$.",
    concept: "Decimal digit constraints",
  },
  // TamasSimonds/imo-dataset · 1962 Problem 1
  {
    id: "imo-1962-p1",
    domain: "Number Theory",
    source: "IMO",
    question: "What is the smallest natural number ending in $6$ that becomes four times its original value when its last digit is moved to the front?",
    options: ["$153846$", "$1538460$", "$615384$", "$384615$"],
    correctIdx: 0,
    a: 2.1,
    b: 2.3,
    c: 0.25,
    hint: "Write the number as $10a+6$ and impose the digit rotation equation.",
    concept: "Digit rotation",
  },
  // TamasSimonds/imo-dataset · 1968 Problem 2
  {
    id: "imo-1968-p2",
    domain: "Number Theory",
    source: "IMO",
    question: "Which natural number has digit product equal to $x^2-10x-22$, where $x$ is the number itself?",
    options: ["$12$", "$11$", "$22$", "$24$"],
    correctIdx: 0,
    a: 2.1,
    b: 2.5,
    c: 0.25,
    hint: "The digit product cannot exceed $x$, giving a short range to check.",
    concept: "Digit products",
  },
];

/** Groups items by their placement level source, for reporting and bank browsing. */
export function itemsBySource() {
  const groups = new Map<string, IRTItem[]>();
  for (const item of ITEM_BANK) {
    const list = groups.get(item.source) || [];
    list.push(item);
    groups.set(item.source, list);
  }
  return groups;
}
