import { useState } from 'react';
import { ArrowDown, ArrowRight, ArrowUpRight, Check, Menu, X } from 'lucide-react';
import TrianglePlayground from './TrianglePlayground';
import '../../styles/landing-refresh.css';

interface LandingPageProps {
  liveStats: { registeredUsers: number; testsCompleted: number; problemsSolved: number };
  onSignIn: () => void;
  onRegister: () => void;
}
const questions = [
  { topic: 'Algebra', title: 'Is there a shorter way?', thought: 'Sometimes the useful step is the one you don’t have to take.', formula: '(a + b)² − (a − b)²', note: 'Expand it. Or look a little closer.' },
  { topic: 'Geometry', title: 'What stays the same?', thought: 'Move a point. Turn a shape. Notice what refuses to change.', formula: 'A = ½ × base × height', note: 'A different shape can hold the same space.' },
  { topic: 'Combinatorics', title: 'Have we counted it twice?', thought: 'A good counting argument starts by deciding what makes two things different.', formula: 'AB = BA ?', note: 'The order matters. Until it doesn’t.' },
  { topic: 'Number Theory', title: 'Can you see the rhythm?', thought: 'Look past the size of a number. A remainder might tell you more.', formula: '2, 4, 1, 2, 4, 1, …', note: 'Powers of two, seen through remainders of seven.' },
];

export default function LandingPage({ onSignIn, onRegister }: LandingPageProps) {
  const [menuOpen, setMenuOpen] = useState(false);
  const [activeQuestion, setActiveQuestion] = useState(0);
  const [noteOpen, setNoteOpen] = useState(false);
  const current = questions[activeQuestion];
  return <div className="quiet-calculix">
    <a className="cq-skip" href="#cq-main">Skip to the question</a>
    <header className="cq-masthead cq-width">
      <a className="cq-wordmark" href="/?home=1" aria-label="CalculixHub home"><span className="cq-symbol" aria-hidden="true"><svg viewBox="0 0 40 40" fill="none"><path d="M30 9C11 2 2 27 18 32c7 3 15-3 15-10M7 23 32 12" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"/><circle cx="31" cy="12" r="3" fill="currentColor"/></svg></span>calculix<span>hub</span></a>
      <span className="cq-masthead-note">A place to think.</span>
      <nav className={menuOpen ? 'cq-navigation is-open' : 'cq-navigation'} aria-label="Main navigation"><a href="#playground" onClick={() => setMenuOpen(false)}>Take a moment</a><a href="#find-a-question" onClick={() => setMenuOpen(false)}>Find a question</a><a href="/?demo=1">My workspace <ArrowUpRight size={13}/></a></nav>
      <button className="cq-signin" onClick={onSignIn}>Sign in <ArrowRight size={15}/></button><button className="cq-menu" aria-label={menuOpen ? 'Close menu' : 'Open menu'} aria-expanded={menuOpen} onClick={() => setMenuOpen(v=>!v)}>{menuOpen ? <X size={20}/> : <Menu size={20}/>}</button>
    </header>
    <main id="cq-main">
      <section className="cq-opening cq-width" aria-labelledby="cq-opening-title"><div className="cq-opening-title"><span className="cq-small-intro">Mathematics, at your own pace.</span><h1 id="cq-opening-title">Stay with<br />the <span>question<svg viewBox="0 0 530 22" aria-hidden="true"><path d="M3 14C150 3 331 5 526 12"/></svg></span>.</h1></div><div className="cq-opening-aside"><p>You don’t have to see it straight away.</p><p>A little space to explore. A useful nudge when you need one. And that quiet satisfaction when something finally makes sense.</p><a href="#playground" className="cq-down-link"><span>Start with this one</span><ArrowDown size={18}/></a></div></section>
      <div className="cq-width cq-playground-wrap"><TrianglePlayground/><div className="cq-afterthought"><span>There’s more than one way to understand something.</span><a href="/?demo=1&tab=learn">Find your own way in <ArrowRight size={14}/></a></div></div>
      <section className="cq-question-shelf cq-width" id="find-a-question" aria-labelledby="cq-shelf-title"><div className="cq-shelf-heading"><h2 id="cq-shelf-title">What’s on<br />your mind?</h2><p>Follow a question that interests you.<br />You can always take a different path.</p></div><div className="cq-shelf-content"><div className="cq-subjects" role="tablist" aria-label="Explore a mathematical idea">{questions.map((question,i)=><button key={question.topic} id={`cq-subject-${i}`} role="tab" aria-selected={i===activeQuestion} aria-controls="cq-question-panel" tabIndex={i===activeQuestion?0:-1} onClick={()=>setActiveQuestion(i)} onKeyDown={event=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();const next=event.key==='Home'?0:event.key==='End'?questions.length-1:(activeQuestion+(event.key==='ArrowRight'?1:-1)+questions.length)%questions.length;setActiveQuestion(next);document.getElementById(`cq-subject-${next}`)?.focus();}}}>{question.topic}</button>)}</div><div className="cq-question-panel" id="cq-question-panel" role="tabpanel" aria-labelledby={`cq-subject-${activeQuestion}`}><div className="cq-notebook-question"><span className="cq-fold" aria-hidden="true"/><span className="cq-question-margin" aria-hidden="true"/><span className="cq-notation">{current.formula}</span><span className="cq-paper-note">{current.note}</span></div><div className="cq-question-invitation"><h3>{current.title}</h3><p>{current.thought}</p><a className="cq-underlined-link" href={`/?demo=1&tab=learn&topic=${encodeURIComponent(current.topic)}`}>Spend some time with {current.topic.toLowerCase()} <ArrowUpRight size={16}/></a></div></div></div></section>
      <section className="cq-open-letter cq-width"><div className="cq-letter-rule"><span aria-hidden="true">↳</span><p>A note before you begin</p></div><div className="cq-letter-body"><h2>You’re allowed<br />to <span>not know yet.</span></h2><p>To cross something out. To try a smaller example. To put a problem down and come back to it.</p><p>We built CalculixHub for that part of learning. The working-it-out part. A place to sit with a question, follow an idea, and gradually make it your own.</p><p className="cq-letter-signoff">Bring a little patience. We’ll bring the questions.</p><button className="cq-note-toggle" onClick={()=>setNoteOpen(value=>!value)} aria-expanded={noteOpen}>What happens when I get stuck? <span>{noteOpen?'−':'+'}</span></button>{noteOpen&&<div className="cq-expanded-note"><p>Begin with a hint. It gives you a direction without taking the discovery away. When you’re ready, read the worked solution and compare it with your own approach. You can revisit a problem as often as you need.</p><a href="/?demo=1&tab=learn">Open a practice problem <ArrowRight size={14}/></a></div>}</div><div className="cq-margin-drawing" aria-hidden="true"><svg viewBox="0 0 200 245" fill="none"><path d="M30 201H175M52 222V39" className="cq-sketch-axis"/><path d="M24 174C53 200 52 72 80 115S104 187 124 78S151 79 170 36" className="cq-sketch-line"/><path d="m168 35-13 8m13-8 2 14" className="cq-sketch-line"/><circle cx="79" cy="116" r="20" className="cq-sketch-circle"/><text x="23" y="244">progress is rarely a straight line.</text></svg></div></section>
      <section className="cq-begin cq-width" aria-labelledby="cq-begin-title"><div><p className="cq-small-intro">Whenever you’re ready.</p><h2 id="cq-begin-title">Pull up a chair.</h2><p>A good question is a perfectly good place to start.</p></div><div className="cq-begin-actions"><a className="cq-primary-link" href="/?demo=1&tab=learn">Choose a question <span><ArrowUpRight size={19}/></span></a><button onClick={onRegister}>Not sure where to begin? Find my level <ArrowRight size={14}/></button></div></section>
    </main>
    <footer className="cq-footer cq-width"><div className="cq-footer-top"><a className="cq-wordmark" href="/?home=1">calculix<span>hub</span><span className="cq-footer-period">.</span></a><div><p>Keep a little room for a good question.</p><a href="/?preview=ios">Take a look at the iPhone experience <ArrowUpRight size={13}/></a></div></div><div className="cq-footer-bottom"><span>Made for the working-it-out part.</span><a href="/?demo=1&tab=community">Find company in the conversation <ArrowRight size={13}/></a><span>© {new Date().getFullYear()} CalculixHub</span></div></footer>
  </div>;
}
