/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Row shapes for the tables in `supabase/migrations/`.
 *
 * Hand-written rather than generated by `supabase gen types`, because that
 * command needs a running project and this file has to compile in CI, on a
 * fresh clone, and in the migration tests -- none of which have one. The trade
 * is that it can drift from the schema, so `schema.test.ts` asserts the columns
 * these types claim actually exist.
 *
 * Only the columns the client reads are modelled. Anything the client must not
 * write (points, grades, counters) is typed read-only at the call sites in
 * `src/lib/data/`, and enforced for real by row-level security.
 */

export type Topic = 'Algebra' | 'Geometry' | 'Combinatorics' | 'Number Theory';
export type Level = 'Foundation' | 'Intermediate' | 'Advanced' | 'Olympiad';

export interface ProfileRow {
  id: string;
  username: string;
  display_name: string;
  avatar_url: string | null;
  bio: string | null;
  country: string | null;
  level: Level;
  follower_count: number;
  following_count: number;
  onboarded_at: string | null;
  created_at: string;
}

export interface UserStatsRow {
  user_id: string;
  points: number;
  attempts_total: number;
  attempts_correct: number;
  problems_solved: number;
  time_spent_seconds: number;
  current_streak: number;
  longest_streak: number;
  last_active_on: string | null;
}

export interface SkillMasteryRow {
  user_id: string;
  topic: Topic;
  attempts: number;
  correct: number;
  mastery: number;
  last_activity_at: string | null;
}

export interface LeaderboardRow {
  rank: number;
  user_id: string;
  username: string;
  display_name: string;
  avatar_url: string | null;
  country: string | null;
  level: Level;
  points: number;
  problems_solved: number;
  current_streak: number;
  accuracy_pct: number | null;
}

export type Reaction = 'like' | 'love' | 'care' | 'haha' | 'wow' | 'sad' | 'angry';

export interface PostRow {
  id: string;
  author_id: string;
  problem_id: string | null;
  community_id: string | null;
  body: string;
  like_count: number;
  comment_count: number;
  deleted_at: string | null;
  created_at: string;
  updated_at: string;
  /**
   * The columns below arrive with `20261004000100_community_social.sql`. They
   * are optional because the client keeps working against a database that has
   * not had that migration applied yet.
   */
  edited_at?: string | null;
  shared_post_id?: string | null;
  share_count?: number;
  /** Storage paths in the `community-media` bucket. */
  images?: string[];
}

export interface CommentRow {
  id: string;
  post_id: string;
  author_id: string;
  body: string;
  like_count: number;
  deleted_at: string | null;
  created_at: string;
  parent_id?: string | null;
  edited_at?: string | null;
  images?: string[];
}

export type NotificationType =
  | 'follow'
  | 'post_like'
  | 'comment_like'
  | 'post_comment'
  | 'message'
  | 'system'
  | 'comment_reply'
  | 'mention'
  | 'post_share';

export interface NotificationRow {
  id: string;
  user_id: string;
  actor_id: string | null;
  type: NotificationType;
  entity_type: 'post' | 'comment' | 'conversation' | 'profile' | null;
  entity_id: string | null;
  body: string | null;
  read_at: string | null;
  created_at: string;
  /** Where a community notification opens: the post, and the comment within it. */
  post_id?: string | null;
  comment_id?: string | null;
}

export interface MessageRow {
  id: string;
  conversation_id: string;
  sender_id: string;
  body: string;
  deleted_at: string | null;
  created_at: string;
}

export interface ConversationRow {
  id: string;
  title: string | null;
  created_by: string | null;
  last_message_at: string | null;
  created_at: string;
}

export type AuthorSummary = Pick<ProfileRow, 'id' | 'username' | 'display_name' | 'avatar_url' | 'level'>;

/** How many of each reaction something has received. Missing keys are zero. */
export type ReactionCounts = Partial<Record<Reaction, number>>;

/** The original a share points at, as the share renders it. */
export type SharedPost = Pick<PostRow, 'id' | 'author_id' | 'problem_id' | 'body' | 'deleted_at' | 'created_at' | 'images'> & {
  author: AuthorSummary | null;
};

/** A post joined with its author, which is how every feed renders one. */
export interface PostWithAuthor extends PostRow {
  author: AuthorSummary | null;
  /** Whether the signed-in learner has liked this post. Absent when anonymous. */
  viewer_has_liked?: boolean;
  viewer_has_saved?: boolean;
  /** The signed-in learner's reaction, or null. Absent when anonymous. */
  viewer_reaction?: Reaction | null;
  reactions?: ReactionCounts;
  /**
   * The original, when this post is a share. Null when the original is gone or
   * hidden from this viewer -- the feed renders that as unavailable.
   */
  shared_post?: SharedPost | null;
}

export interface CommentWithAuthor extends CommentRow {
  author: AuthorSummary | null;
  viewer_reaction?: Reaction | null;
  reactions?: ReactionCounts;
}

export interface NotificationWithActor extends NotificationRow {
  actor: Pick<ProfileRow, 'id' | 'username' | 'display_name' | 'avatar_url'> | null;
}
