import type { Topic } from '../shared/types';

/** Distinct advanced proof exercises; preparation material, not official papers. */
const exercises: Record<Topic, Array<[string, string, string, string, number, number]>> = {
  Algebra: [
    ['An inequality with a sharp remainder', 'For nonnegative $a,b,c$, prove $a^3+b^3+c^3+3abc\\ge ab(a+b)+bc(b+c)+ca(c+a)$ and determine all equality cases.', 'Factor the difference using an ordering of the variables.', 'Order $a\\ge b\\ge c$. The difference is $(a-b)^2(a+b-c)+c(a-c)(b-c)$. Both terms are nonnegative. Equality holds when all three variables are equal, or when one is zero and the other two are equal (including the all-zero case).', 6, 5],
    ['An integer polynomial obstruction', 'Prove that no polynomial with integer coefficients satisfies $P(0)=0$ and $P(1)=P(2)=1$.', 'Factor P, then compare its values at 1 and 2.', 'Since P(0)=0, write $P(x)=xQ(x)$ with Q having integer coefficients. Then $P(2)=2Q(2)$ is even, contradicting P(2)=1.', 3, 3],
    ['Convexity without calculus', 'For positive $x_1,\\ldots,x_n$ with sum 1, prove $\\sum_{i=1}^n1/x_i\\ge n^2$ and determine equality.', 'Use Cauchy with reciprocal square roots.', 'Cauchy gives $(\\sum x_i)(\\sum1/x_i)\\ge(\\sum1)^2=n^2$. Equality requires all x_i equal, hence each is 1/n. These values attain the bound.', 4, 3],
    ['A multiplicative and additive map', 'Determine every function $f:\\mathbb R\\to\\mathbb R$ satisfying both $f(x+y)=f(x)+f(y)$ and $f(xy)=f(x)f(y)$.', 'First consider f(1), then nonnegative squares.', 'Multiplicativity gives f(1)=0 or 1. The first case gives f identically zero. In the second, $f(t^2)=f(t)^2\\ge0$, so additivity makes f monotone: x<y implies f(y)−f(x)=f(y−x)≥0. Additivity fixes every rational. Rational upper and lower approximations then force f(x)=x for every real. Both maps satisfy the equations.', 7, 5],
    ['Interpolation from roots', 'Let P be a real polynomial of degree at most n. Prove $P(x)=\\sum_{i=0}^nP(i)\\prod_{0\\le j\\le n,\\ j\\ne i}(x-j)/(i-j)$.', 'Compare both sides at n+1 points.', 'Each product is 1 at x=i and 0 at every other integer from 0 through n. Subtract the proposed expression from P. The difference has degree at most n and n+1 distinct roots, so vanishes identically.', 5, 4],
    ['A symmetric fourth-power bound', 'For real a,b,c, prove $(a^2+b^2+c^2)^2\\ge3(a^2b^2+b^2c^2+c^2a^2)$ and determine equality.', 'Treat the squares as three new variables.', 'Subtracting the right side leaves $\\tfrac12((a^2-b^2)^2+(b^2-c^2)^2+(c^2-a^2)^2)$. This is nonnegative and vanishes exactly when $|a|=|b|=|c|$.', 4, 3],
    ['A recurrence and its invariant', 'Let $u_0=0,u_1=1$ and $u_{n+1}=3u_n-u_{n-1}$. Prove $u_{n+1}u_{n-1}-u_n^2=-1$ for every n≥1.', 'Show the expression remains unchanged between consecutive indices.', 'Using $u_{n-1}=3u_n-u_{n+1}$, the expression is $3u_nu_{n+1}-u_{n+1}^2-u_n^2$. Replacing $u_{n+2}=3u_{n+1}-u_n$ shows the next expression is identical. At n=1 it equals −1, proving the result by induction.', 6, 4],
  ],
  Geometry: [
    ['Euler’s geometric inequality', 'Prove R≥2r for every nondegenerate triangle, and show equality holds only for an equilateral triangle.', 'Use the squared distance between the incenter and circumcenter.', 'Euler’s identity $OI^2=R(R-2r)$ and R>0 imply R≥2r. Equality means O=I. The center then has equal distances to the three chords AB,BC,CA; equal-distance chords have equal lengths, hence the triangle is equilateral. The equilateral triangle attains equality.', 6, 5],
    ['Stewart’s identity', 'For D on BC, set BD=m, DC=n, AD=d, AB=c, AC=b. Prove $b^2m+c^2n=(m+n)(d^2+mn)$.', 'Resolve lengths along BC and cancel the cross terms.', 'Set D=(0,0), B=(−m,0), C=(n,0), A=(x,y). Then $c^2=(x+m)^2+y^2$, $b^2=(x-n)^2+y^2$, and $d^2=x^2+y^2$. Multiply b² by m and c² by n; the linear terms cancel, leaving $(m+n)(d^2+mn)$.', 5, 4],
    ['Trigonometric Ceva', 'For interior side points D,E,F in triangle ABC, prove concurrency of AD,BE,CF is equivalent to $\\frac{\\sin BAD}{\\sin DAC}\\frac{\\sin CBE}{\\sin EBA}\\frac{\\sin ACF}{\\sin FCB}=1$.', 'Convert angle ratios to side ratios using sine-area formulas.', 'Area ratios give $BD/DC=(AB/AC)\\sin BAD/\\sin DAC$. Similarly $CE/EA=(BC/BA)\\sin CBE/\\sin EBA$ and $AF/FB=(CA/CB)\\sin ACF/\\sin FCB$. Multiply; the side factors cancel. Ordinary Ceva supplies both directions.', 7, 5],
    ['The medial triangle’s circle', 'Prove the circle through the three side midpoints of a triangle has radius R/2, where R is the original circumradius.', 'Apply a homothety centered at the centroid.', 'The homothety with center G and ratio −1/2 sends each vertex to the midpoint of the opposite side: in vector form $G-(A-G)/2=(B+C)/2$. It sends the circumcircle to the circle through all three midpoints and scales its radius to R/2.', 5, 4],
    ['Ptolemy’s inequality', 'For any four distinct points A,B,C,D in the plane, prove $AC\\cdot BD\\le AB\\cdot CD+AD\\cdot BC$.', 'Invert about A and apply the triangle inequality.', 'Use inversion of unit radius centered at A. For points X,Y different from A, $X^{\\prime}Y^{\\prime}=XY/(AX\\cdot AY)$. The triangle inequality $B^{\\prime}D^{\\prime}\\le B^{\\prime}C^{\\prime}+C^{\\prime}D^{\\prime}$, multiplied by AB·AC·AD, yields the required inequality. The inversion distance formula follows by expanding the squared vector distance.', 7, 5],
    ['An orthocenter as a reflection', 'In acute triangle ABC, prove that reflection of the orthocenter H across BC lies on the circumcircle.', 'Track the angle between the two reflected altitude segments.', 'The altitude perpendicularities give $\\angle BHC=180^\\circ-\\angle A$. Reflecting H across BC produces H′ on the other side of BC with the same angle $\\angle BH^{\\prime}C$. A and H′ lie on opposite sides of BC and their angles sum to 180°, so A,B,H′,C are concyclic.', 6, 4],
    ['A sum of squared medians', 'For a triangle with side lengths a,b,c and corresponding medians m_a,m_b,m_c, prove $m_a^2+m_b^2+m_c^2=3(a^2+b^2+c^2)/4$.', 'Apply the median identity on all three sides.', 'Apollonius gives $4m_a^2=2b^2+2c^2-a^2$ and its two cyclic counterparts. Adding yields $4(m_a^2+m_b^2+m_c^2)=3(a^2+b^2+c^2)$.', 4, 3],
  ],
  Combinatorics: [
    ['Sperner’s bound', 'Prove a family of subsets of an n-element set, no one containing another, has size at most $\\binom n{\\lfloor n/2\\rfloor}$.', 'Count permutations whose prefix sets include a member of the family.', 'A k-element member is a prefix set in k!(n−k)! permutations. No permutation can have two members as prefixes because prefixes are nested. Thus $\\sum_{A}1/\\binom n{|A|}\\le1$. Every denominator is at most the central binomial coefficient, yielding the bound; all subsets of size floor(n/2) attain it.', 8, 5],
    ['A tournament path', 'Prove every finite tournament has a directed Hamiltonian path.', 'Insert a new vertex into an existing directed path.', 'Induct on vertices. Given path v₁→…→vₖ, append a new vertex x if every v_i points to x. Otherwise take the first j with x→v_j. If j=1 put x first; otherwise v_{j−1}→x by minimality, so insert x before v_j. Every new adjacent edge points forward.', 6, 4],
    ['A Ramsey recurrence', 'Prove $R(r,s)\\le R(r-1,s)+R(r,s-1)$ for r,s≥3.', 'Partition neighbours of one vertex by edge colour.', 'Set a=R(r−1,s), b=R(r,s−1) and consider K_{a+b}. At one vertex, either at least a edges are red or at least b are blue. In the red-neighbour set, a red K_{r−1} extends with the vertex, or a blue K_s already exists. The blue-neighbour case is symmetric.', 7, 5],
    ['Catalan convolution', 'Let C_n count correctly matched strings of n pairs of parentheses. Prove $C_{n+1}=\\sum_{k=0}^nC_kC_{n-k}$ with C_0=1.', 'Locate the closing parenthesis matching the first opening one.', 'A nonempty balanced string uniquely decomposes as (U)V, with U and V balanced. If U has k pairs, V has n−k pairs. There are C_k C_{n−k} choices; summing over the disjoint possibilities gives the formula.', 5, 4],
    ['A dominating independent set', 'Prove every finite graph has an independent set S such that every vertex outside S has a neighbour in S.', 'Choose an independent set maximal under inclusion.', 'A finite graph has an inclusion-maximal independent set. If an outside vertex had no neighbour in it, that vertex could be added while preserving independence, contradicting maximality. Thus the set dominates all outside vertices.', 4, 3],
    ['Euler’s planar count', 'Prove a connected plane graph with V vertices, E edges and F faces satisfies V−E+F=2.', 'Remove edges on cycles until only a tree remains.', 'A tree has E=V−1 and one face, hence the identity. If a connected plane graph has a cycle, remove a cycle edge: connectivity remains, E falls by one, and the two adjacent faces merge, so F falls by one. Repeating reaches a tree and preserves V−E+F.', 7, 4],
    ['A double-counted intersection', 'A family contains m subsets of an n-element set, each of size k. Prove some element belongs to at least $\\lceil mk/n\\rceil$ members.', 'Count incidences between elements and members.', 'Count pairs (x,A) with x in A. Summing over members gives mk. If every element belonged to fewer than ceil(mk/n) members, the total would be below mk; equivalently some element has membership at least the average mk/n and hence its ceiling.', 4, 3],
  ],
  'Number Theory': [
    ['Primes congruent to one', 'Prove infinitely many primes are congruent to 1 modulo 4.', 'A prime dividing a square plus one has −1 as a quadratic residue.', 'Suppose the list is p₁,…,pₖ. Set M=2p₁···pₖ and N=M²+1. N is odd and no listed prime divides it. For any prime q dividing N, M²≡−1 modulo q, so M has multiplicative order 4. By Lagrange, 4 divides q−1. This yields an unlisted prime congruent to 1 modulo 4.', 7, 5],
    ['An order divisibility rule', 'Let gcd(a,m)=1 and let d be the least positive integer with $a^d\\equiv1\\pmod m$. Prove $a^k\\equiv1\\pmod m$ exactly when d divides k, for k≥0.', 'Divide k by d with remainder.', 'Write k=qd+r with 0≤r<d. If a^k≡1, then a^r≡1 because a^d≡1. Minimality forces r=0. Conversely a^{qd}≡1. Existence of d follows because the invertible residues form a finite group.', 5, 4],
    ['A square modulo an odd prime', 'For an odd prime p, prove $x^2\\equiv1\\pmod p$ has exactly the residues x≡1 and x≡−1.', 'Use the absence of zero divisors modulo a prime.', 'The congruence is equivalent to p dividing (x−1)(x+1). Primality forces p to divide one factor. Both residues satisfy the congruence and are distinct because p is odd.', 3, 3],
    ['An integer divisibility descent', 'Prove gcd(a,b)=gcd(b,a−qb) for all integers a,b,q, not both a,b zero, and use this to justify the Euclidean algorithm.', 'Compare common divisors in both directions.', 'Every common divisor of a,b divides a−qb. Conversely, every common divisor of b,a−qb divides a=(a−qb)+qb. The common divisor sets are identical. Choosing a remainder of smaller absolute value makes successive nonzero remainders decrease, so the algorithm terminates with the gcd.', 5, 3],
    ['A prime binomial congruence', 'Prove $(a+b)^p\\equiv a^p+b^p\\pmod p$ for prime p and arbitrary integers a,b.', 'Show every interior binomial coefficient is divisible by p.', 'For 1≤k≤p−1, the numerator p! contains p while k!(p−k)! does not. Thus p divides the integer binomial coefficient. Expanding (a+b)^p leaves only the two endpoint terms modulo p.', 5, 4],
    ['The two-square obstruction', 'Prove no integer congruent to 3 modulo 4 is the sum of two integer squares.', 'List square residues modulo 4.', 'An even square is 0 modulo 4 and an odd square is 1. The possible sums are 0,1,2; none is 3. Therefore such a representation is impossible.', 3, 2],
    ['Bézout from a minimum', 'Prove that for positive integers a,b there are integers x,y with ax+by=gcd(a,b).', 'Choose the least positive integer of the form ax+by.', 'The set of positive integer combinations is nonempty. Let d be its minimum. Dividing a by d gives a remainder also of the form ax+by; minimality forces that remainder to be zero. Likewise d divides b. Every common divisor of a,b divides d, so d is the gcd and its defining combination supplies x,y.', 7, 5],
  ],
};

export function olympiadExtension(topic: Topic, index: number) {
  const [title, question, hint, solution, steps, abstraction] = exercises[topic][index];
  return { title, question, hint, solution, steps, abstraction, answer: 'PROOF', numeric: false };
}
