import { useEffect, useState } from 'react';
import { ArrowUpRight, Check } from 'lucide-react';
import '../../styles/iphone-prototype.css';
/** The phone hosts the real app, sharing the same account, database and live subscriptions. */
export default function IPhonePrototype() {
 const [scale,setScale]=useState(1);
 useEffect(()=>{const size=()=>setScale(Math.min(1,Math.max(.5,(window.innerWidth-32)/411),(window.innerHeight-70)/870));size();window.addEventListener('resize',size);return()=>window.removeEventListener('resize',size);},[]);
 return <main className="iphone-presentation"><section className="ip-presentation-copy"><div className="ip-presentation-eyebrow">THE CALCULIXHUB MOBILE EXPERIENCE</div><h1>Big ideas.<br/><span>Pocket size.</span></h1><p>Your real learning space, in a smaller frame. Sign in with the same account to pick up where you left off.</p><div className="ip-presentation-features"><span><Check size={15}/> Your saved questions and progress</span><span><Check size={15}/> The same live arenas and conversations</span></div><div className="ip-presentation-instruction"><ArrowUpRight size={20}/><p>Tap, explore, solve. This phone uses the real application.</p></div><a href="/?demo=1">Open the full workspace</a></section><div className="ip-device-area"><div className="ip-mobile-preview-label">iPhone 16 · Live workspace</div><div className="ip-device-scaler" style={{width:411*scale,height:870*scale}}><div className="ip-device" style={{transform:`scale(${scale})`}}><span className="ip-hardware-button ip-action-button" aria-hidden="true"/><span className="ip-hardware-button ip-volume-up" aria-hidden="true"/><span className="ip-hardware-button ip-volume-down" aria-hidden="true"/><span className="ip-hardware-button ip-power-button" aria-hidden="true"/><div className="ip-screen"><div className="ip-status-bar" aria-hidden="true"><span>CalculixHub</span><div className="ip-dynamic-island"/></div><iframe title="CalculixHub live mobile workspace" src="/?demo=1" style={{width:'100%',flex:1,border:0,minHeight:0}}/><div className="ip-home-indicator" aria-hidden="true"><span/></div></div></div></div></div></main>;
}
