-- CalculixHub: notifications and realtime.
--
-- Notifications are generated by database triggers on the actions that cause
-- them, not by the client that performed the action. A client-generated
-- notification is one the client can forge, omit, or simply fail to send when a
-- request is interrupted halfway. Generating them in the same transaction as
-- the like or the follow makes them exactly as reliable as the action itself.

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),

  -- Who sees it.
  user_id uuid not null references public.profiles(id) on delete cascade,
  -- Who caused it. Nullable so a system notification has no actor.
  actor_id uuid references public.profiles(id) on delete cascade,

  type text not null check (type in (
    'follow', 'post_like', 'comment_like', 'post_comment', 'message', 'system'
  )),

  -- Loose references: the target may be a post, comment or conversation, and a
  -- typed FK per kind would mean five nullable columns and five join paths.
  entity_type text check (entity_type is null or entity_type in ('post', 'comment', 'conversation', 'profile')),
  entity_id uuid,

  body text check (body is null or length(body) <= 500),

  read_at timestamptz,
  created_at timestamptz not null default now()
);

-- Serves the unread badge directly: a partial index over unread rows only,
-- which stays small no matter how much history accumulates.
create index if not exists notifications_unread_idx
  on public.notifications (user_id, created_at desc)
  where read_at is null;

create index if not exists notifications_user_idx
  on public.notifications (user_id, created_at desc);

-- Collapses duplicates. Liking, unliking and re-liking a post should not
-- produce three notifications; the unique index makes the second one a no-op.
create unique index if not exists notifications_dedupe_key
  on public.notifications (user_id, actor_id, type, entity_id)
  where actor_id is not null and entity_id is not null;

-- ---------------------------------------------------------------------------
-- Generation
-- ---------------------------------------------------------------------------

-- Central insert. Self-directed notifications are dropped here rather than in
-- each caller: nobody needs telling that they liked their own post.
create or replace function public.emit_notification(
  recipient uuid,
  actor uuid,
  notification_type text,
  entity_kind text,
  entity uuid,
  message text default null
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if recipient is null or recipient = actor then
    return;
  end if;

  insert into public.notifications (user_id, actor_id, type, entity_type, entity_id, body)
  values (recipient, actor, notification_type, entity_kind, entity, message)
  on conflict do nothing;
end;
$$;

create or replace function public.notify_on_follow()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  perform public.emit_notification(new.following_id, new.follower_id, 'follow', 'profile', new.follower_id);
  return null;
end;
$$;

create trigger follows_notify
  after insert on public.follows
  for each row execute function public.notify_on_follow();

create or replace function public.notify_on_post_like()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  post_author uuid;
begin
  select author_id into post_author from public.posts where id = new.post_id;
  perform public.emit_notification(post_author, new.user_id, 'post_like', 'post', new.post_id);
  return null;
end;
$$;

create trigger post_likes_notify
  after insert on public.post_likes
  for each row execute function public.notify_on_post_like();

create or replace function public.notify_on_comment()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  post_author uuid;
begin
  select author_id into post_author from public.posts where id = new.post_id;
  perform public.emit_notification(
    post_author, new.author_id, 'post_comment', 'post', new.post_id,
    left(new.body, 140)
  );
  return null;
end;
$$;

create trigger comments_notify
  after insert on public.comments
  for each row execute function public.notify_on_comment();

create or replace function public.notify_on_message()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  -- One notification per other participant, so group threads work unchanged.
  perform public.emit_notification(
    p.user_id, new.sender_id, 'message', 'conversation', new.conversation_id,
    left(new.body, 140)
  )
  from public.conversation_participants p
  where p.conversation_id = new.conversation_id and p.user_id <> new.sender_id;

  return null;
end;
$$;

create trigger messages_notify
  after insert on public.messages
  for each row execute function public.notify_on_message();

-- ---------------------------------------------------------------------------
-- Row-level security
-- ---------------------------------------------------------------------------

alter table public.notifications enable row level security;

create policy notifications_select_own
  on public.notifications for select
  using (auth.uid() = user_id);

-- Marking as read is the only client-writable change. No insert policy exists:
-- notifications come from triggers, so a client cannot manufacture one that
-- appears to be from someone else.
create policy notifications_update_own
  on public.notifications for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy notifications_delete_own
  on public.notifications for delete
  using (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- Realtime
-- ---------------------------------------------------------------------------

-- Adds the tables whose changes clients subscribe to.
--
-- Realtime respects RLS on every broadcast, so a subscriber receives only rows
-- their policies already allow -- adding a table here does not widen access. It
-- is guarded because `supabase_realtime` is created by the platform and is
-- absent in a bare Postgres, where these migrations must still apply.
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    alter publication supabase_realtime add table
      public.posts,
      public.comments,
      public.post_likes,
      public.comment_likes,
      public.messages,
      public.notifications,
      public.user_stats;
  end if;
end $$;

-- Realtime needs the full old row to evaluate RLS on DELETE and UPDATE events;
-- the default only replicates the primary key, which is not enough to decide
-- whether a subscriber was entitled to see the row that changed.
alter table public.posts replica identity full;
alter table public.comments replica identity full;
alter table public.post_likes replica identity full;
alter table public.comment_likes replica identity full;
alter table public.messages replica identity full;
alter table public.notifications replica identity full;
